name: Continuous Deployment

on:                                                       
  push:
    branches:
      - production                                        
    paths-ignore:
      - 'README.md'                                       

jobs:
  build:
    runs-on:                                              
      - ubuntu-latest
    strategy:                                             
      matrix:
        node-verzija:
          - 12.x
    steps:                                                
      - uses: actions/checkout@v2                        
      - name: Use Node.js ${{ matrix.node-verzija }}  
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-verzija }}
      - run: npm install                                  
                                                          
      - shell: bash
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_PRODUCTION: ${{ secrets.HEROKU_PRODUCTION }}
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PRODUCTION.git production:master --force
